-- Add price fields to styles table
ALTER TABLE styles ADD COLUMN IF NOT EXISTS cost_rmb DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE styles ADD COLUMN IF NOT EXISTS price_hkd DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE styles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
